#!/usr/bin/python

# Diffie-Hellman Key Exchange.

import sys
import random 
import time
import primes 

# Generated by helper script primes.py 
p = primes.get_random_prime()
g = primes.primitive_root(p)

if len(sys.argv) != 3 and len(sys.argv) != 1:
    err = sys.argv[0] + " g p"
    print("Expected: " + err)
    sys.exit()

# Command line arguments for p and g 
if len(sys.argv) == 3:
    p = int(sys.argv[1])
    g = int(sys.argv[2])

maxSecret = 1000

# Compute shared secret key 
def SharedSecret(result, secret):
    return result**secret % p

# Compute result 
def compute(secret):
    return g**secret % p


# secrets 
a = random.randrange(1, maxSecret + 1)
b = random.randrange(1, maxSecret + 1)

# Results of g**secret % p
A = compute(a)
B = compute(b)


print("Publicly Shared Variables:")
print("Publicly Shared Prime: " + str(p))
print("Publicly Shared Base: " + str(g))
print(" Alice secret: " + str(a))
print(" Bob secret: " + str(b))
print("  Alice Sends Over Public Chanel: " + str(A))
print("  Bob Sends Over Public Chanel: " + str(B))


print("------------")
print("Privately Calculated Shared Secret:")
aliceSS = SharedSecret(B, a)
bobSS = SharedSecret(A,b)
print("    Alice Shared Secret: " + str(aliceSS))
print("    Bob Shared Secret: " + str(bobSS))
print("------------")

def bruteForce():
    for i in range(1, maxSecret + 1):
        if compute(i) == A:
            print("Guessed alice secret: " + str(i))
            for j in range(1, maxSecret + 1):
                if compute(j) == B:
                    print("Guessed bob secret: " + str(j))
                    bruteAliceSS = SharedSecret(B, i)
                    bruteBobSS = SharedSecret(A, j)
                    if bruteBobSS == bruteAliceSS:
                        return str(bruteBobSS)

print("\nATTEMPTING BRUTE-FORCE BASED ON INTERCEPTION OF NETWORK TRAFFIC")
t1 = time.time()
print("The secret key is : " + bruteForce())
t2 = time.time()
print("Time taken : " + str(round(t2 - t1, 4)))


# Example output
'''
$ python dh2.py 17 2
Publicly Shared Variables:
    Publicly Shared Prime:  17
    Publicly Shared Base:   2
  Alice Sends Over Public Chanel:  13
   Bob Sends Over Public Chanel:  9
------------
Privately Calculated Shared Secret:
    Alice Shared Secret:  4
    Bob Shared Secret:  4
'''
